name: BUILD_n_TEST
on:
  push:
    branches:
      - main

env:
  APP_NAME: monopoly

jobs:

  build_maven_run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build and test with maven
        run: mvn test --file pom.xml

  build_maven_run_integrationtests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build and run integration test with maven
        run: mvn test -P integration-tests --file pom.xml

  build_maven_run_functionaltests:
    needs:
      - build_maven_run_tests
      - build_maven_run_integrationtests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build and run functional test with maven
        run: mvn test -P functional-tests --file pom.xml